---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/slots":
    post:
      summary: Creates a slot
      tags:
      - Slots
      consumes:
      - application/json
      - application/xml
      parameters:
      - name: slot
        in: body
        schema:
          type: object
          properties:
            user_id:
              type: integer
            datetime_from:
              type: datetime
            datetime_to:
              type: datetime
          required:
          - user_id
          - datetime_from
          - datetime_to
      responses:
        '201':
          description: slot created
        '422':
          description: invalid request
  "/api/v1/slots/{id}":
    get:
      summary: Retrieves a slot
      tags:
      - Slots
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        type: string
        required: true
      responses:
        '200':
          description: blog found
          schema:
            type: object
            properties:
              id:
                type: integer
              user_id:
                type: integer
              datetime_from:
                type: datetime
              datetime_to:
                type: datetime
            required:
            - id
            - user_id
            - datetime_from
            - datetime_to
        '404':
          description: slot not found
        '406':
          description: unsupported accept header
